/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData photo_9_svgrepo_com = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_camera_svgrepo_com = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sneakers_svgrepo_com = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weather_2_svgrepo_com = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sport_jacket_svgrepo_com = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tshirt_svgrepo_com = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jeans_boy_svgrepo_com = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shorts_svgrepo_com = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skirt_svgrepo_com = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_jacket_svgrepo_com = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData evening_dress_svgrepo_com = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoe_5_svgrepo_com = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoe_prints = IconData(0xea98, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
